import {test} from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {Test} from '@nestjs/testing';import {AppModule} from '../dist/src/app.module.js';import {AuthRepository} from '../dist/src/auth/auth.repository.js';
import {fixture,action} from './contract-fixture.mjs';
const integration=process.env.NODE_ENV==='test'&&process.env.DATABASE_URL?test:test.skip;
integration('contract HTTP isolates human consent from MCP and enforces project, CSRF and version boundaries',async()=>{
 const f=await fixture();const {db,a,b,pm,ref,c,p,input}=f;let app;
 try{
  const auth=new AuthRepository(db),sessions=await Promise.all([a,b,pm,ref,c].map(id=>auth.issueSession(id)));
  app=(await Test.createTestingModule({imports:[AppModule.register({nodeEnv:'test',apiPort:0,webPort:0,dbPort:55439,databaseName:'handoff_test',databaseHost:'127.0.0.1',postgresUser:'handoff',postgresPassword:'unused',databaseUrl:process.env.DATABASE_URL})]}).compile()).createNestApplication();app.useLogger(['error']);await app.listen(0,'127.0.0.1');const base=await app.getUrl();
  const call=(path,method='GET',body,who=0,csrf=true,token)=>fetch(base+path,{method,headers:{...(who===null?{}:{Cookie:`ho_session=${sessions[who].token}`}),...(csrf&&who!==null?{'X-CSRF-Token':sessions[who].csrf}:{}),...(token?{Authorization:`Bearer ${token}`}:{ }),'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
  const grant=await call('/api/mcp/grants','POST',{projectId:p}).then(r=>r.json());
  const sent=await call('/api/mcp/contracts','POST',{projectId:p,...input},null,false,grant.token);
  assert.equal(sent.status,201);const r=await sent.json(),path=`/api/projects/${p}/contract-proposals/${r.proposalId}`;
  assert.equal((await call(path)).headers.get('cache-control'),'no-store');
  assert.equal((await call(path,'GET',undefined,4)).status,404);
  assert.equal((await call(path+'/responses','POST',action(1),null,false,grant.token)).status,401);
  assert.equal((await call(path+'/responses','POST',action(1),1,false)).status,403);
  for(const who of [3,4])assert.equal((await call(path+'/responses','POST',action(1),who)).status,404);
  for(const invalid of [{...action(1),version:0},{...action(1),action:'UNKNOWN'},{...action(1,'REQUEST_CHANGES'),comment:' '},{...action(1,'REQUEST_CHANGES'),comment:'x'.repeat(10001)}])assert.equal((await call(path+'/responses','POST',invalid,1)).status,400);
  assert.equal((await call(path+'?version=NaN')).status,400);
  assert.equal((await call(path.replace(p,randomUUID()),'GET')).status,404);
  assert.equal((await call('/api/mcp/contracts','GET',undefined,null,false,grant.token)).headers.get('cache-control'),'no-store');
  assert.deepEqual(await call('/api/mcp/contracts','GET',undefined,null,false,grant.token).then(r=>r.json()),[]);
  assert.equal((await call(path+'/responses','POST',action(1,'REQUEST_CHANGES'),1)).status,201);
  const revision=await call(`/api/mcp/contract-proposals/${r.proposalId}/versions`,'POST',{expectedVersion:1,proposedBody:'revised',requiredPmIds:[pm],referencePmIds:[ref],idempotencyKey:randomUUID()},null,false,grant.token);
  assert.equal(revision.status,201);
  assert.equal((await call(path+'/responses','POST',action(1),0)).status,409);
  await db.projectMembership.delete({where:{projectId_userId:{projectId:p,userId:b}}});
  assert.equal((await call(path+'/responses','POST',action(2),1)).status,404);
  assert.equal((await call(path+'/responses','POST',action(2),0)).status,409);
  await db.projectMembership.create({data:{projectId:p,userId:b,role:'MEMBER'}});
  for(const who of [0,1,2])assert.equal((await call(path+'/responses','POST',action(2),who)).status,201);
  const detail=await call(`/api/projects/${p}/contracts/${r.contractId}`,'GET',undefined,4).then(r=>r.json());assert.equal(detail.body,'revised');assert.ok(!('responses' in detail));
  const active=await call('/api/mcp/contracts','GET',undefined,null,false,grant.token).then(r=>r.json());assert.equal(active.length,1);
  const baseline=(await db.developmentContract.findUnique({where:{id:r.contractId}})).currentVersionId;
  const followupPath=`/api/mcp/contracts/${r.contractId}/proposals`,changeInput={kind:'CHANGE',baselineVersionId:baseline,proposedBody:'new body',requiredPmIds:[],referencePmIds:[],idempotencyKey:randomUUID()};
  assert.equal((await call(followupPath,'POST',changeInput,null,false,grant.token)).status,201);
  const next=await call(followupPath,'POST',changeInput,null,false,grant.token).then(r=>r.json()),withdrawPath=`/api/projects/${p}/contract-proposals/${next.proposalId}/withdraw`;
  const withdraw={expectedVersion:1,reason:'reconsider',idempotencyKey:randomUUID()};
  assert.equal((await call(withdrawPath,'POST',withdraw,null,false,grant.token)).status,401);
  assert.equal((await call(withdrawPath,'POST',withdraw,0,false)).status,403);
  assert.equal((await call(withdrawPath,'POST',withdraw,1)).status,404);
  assert.equal((await call(withdrawPath.replace(p,randomUUID()),'POST',withdraw)).status,404);
  assert.equal((await call(withdrawPath,'POST',{...withdraw,reason:''})).status,400);
  assert.equal((await call(withdrawPath,'POST',{...withdraw,expectedVersion:2})).status,409);
  assert.equal((await call(withdrawPath,'POST',withdraw)).status,201);
  assert.equal((await call(followupPath,'POST',{...changeInput,kind:'RETIRE',baselineVersionId:undefined,idempotencyKey:randomUUID()},null,false,grant.token)).status,400);
  await db.user.update({where:{id:c},data:{status:'PENDING'}});assert.equal((await call(`/api/projects/${p}/contracts/${r.contractId}`,'GET',undefined,4)).status,404);
 }finally{await app?.close();await f.close();}
});
