import assert from 'node:assert/strict';
import { test } from 'node:test';
import { randomUUID, createHash } from 'node:crypto';
import { PrismaService } from '../dist/src/database/prisma.service.js';
import { HandoffRepository } from '../dist/src/handoff/handoff.repository.js';
const integration = process.env.NODE_ENV === 'test' && process.env.DATABASE_URL ? test : test.skip;
const conflict = error => error?.getStatus?.() === 409;

integration('human responses, private changes, revisions and notifications stay versioned and retry-safe', async () => {
  const module = await import('../dist/src/handoff/handoff-workflow.repository.js').catch(() => ({}));
  assert.equal(typeof module.HandoffWorkflowRepository, 'function', 'workflow repository is implemented');
  const db = new PrismaService({ databaseUrl: process.env.DATABASE_URL });
  const flow = new module.HandoffWorkflowRepository(db), requests = new HandoffRepository(db);
  const [a,b,c,p] = Array.from({length:4},()=>randomUUID());
  try {
    await db.user.createMany({data:[a,b,c].map(id=>({id,status:'APPROVED'}))});
    await db.project.create({data:{id:p,name:'workflow',creatorId:a,memberships:{create:[a,b,c].map(userId=>({userId,role:'MEMBER'}))}}});
    const grant = await db.mcpGrant.create({data:{userId:a,projectId:p,tokenHash:createHash('sha256').update(randomUUID()).digest('hex'),expiresAt:new Date(Date.now()+600000)}});
    const r = await requests.createRequest(a,p,{recipientId:b,publicTitle:'Public',privateBody:'v1 private',grantId:grant.id,idempotencyKey:randomUUID()});
    assert.equal((await flow.summary(b,p)).needsReview,1);
    await db.projectMembership.delete({where:{projectId_userId:{projectId:p,userId:a}}});
    assert.equal((await requests.getPrivateRequest(b,r.id)).canRespond,false);
    assert.equal((await flow.summary(b,p)).needsReview,0);
    await db.projectMembership.create({data:{projectId:p,userId:a,role:'MEMBER'}});
    await db.user.update({where:{id:a},data:{status:'PENDING'}});
    assert.equal((await flow.summary(b,p)).needsReview,0);
    await db.user.update({where:{id:a},data:{status:'APPROVED'}});
    await assert.rejects(flow.respond(b,p,r.id,{version:999,action:'ACKNOWLEDGE',idempotencyKey:randomUUID()}),conflict);
    const input={version:1,action:'REQUEST_CHANGES',comment:'only A and B see this',idempotencyKey:randomUUID()};
    const response=await flow.respond(b,p,r.id,input);
    assert.equal((await flow.respond(b,p,r.id,input)).id,response.id);
    await assert.rejects(flow.respond(b,p,r.id,{...input,comment:'changed'}),conflict);
    await assert.rejects(flow.respond(b,p,r.id,{...input,action:'ACKNOWLEDGE',comment:undefined,idempotencyKey:randomUUID()}),conflict);
    assert.equal((await flow.summary(a,p)).needsChanges,1);
    await db.projectMembership.delete({where:{projectId_userId:{projectId:p,userId:b}}});
    assert.equal((await flow.summary(a,p)).needsChanges,0);
    await db.projectMembership.create({data:{projectId:p,userId:b,role:'MEMBER'}});
    assert.equal((await flow.summary(b,p)).needsReview,0);
    const notes=await flow.notifications(a,p);
    assert.equal(notes.length,1); assert.equal(notes[0].kind,'CHANGES_REQUESTED');
    assert.ok(!JSON.stringify(notes).includes('only A'));
    assert.ok(!JSON.stringify(await requests.listFeed(c,p)).includes('only A'));
    assert.ok(!JSON.stringify(await requests.listFeed(c,p)).includes(a));
    await assert.rejects(flow.markRead(c,p,notes[0].id));
    const read=await flow.markRead(a,p,notes[0].id);
    assert.equal(String((await flow.markRead(a,p,notes[0].id)).readAt),String(read.readAt));
    const revision={expectedVersion:1,privateBody:'v2 private',idempotencyKey:randomUUID()};
    const versions=await Promise.all([flow.resend(a,p,r.id,grant.id,revision),flow.resend(a,p,r.id,grant.id,revision)]);
    assert.equal(versions[0].versionId,versions[1].versionId);
    assert.equal(versions[0].version,2);
    assert.equal(await db.handoffVersion.count({where:{requestId:r.id}}),2);
    assert.equal((await requests.getPrivateRequest(a,r.id,1)).privateBody,'v1 private');
    assert.equal((await requests.getPrivateRequest(a,r.id,1)).response.comment,input.comment);
    assert.equal((await requests.getPrivateRequest(b,r.id)).status,'AWAITING_REVIEW');
    assert.equal((await flow.summary(b,p)).needsReview,1);
    await assert.rejects(flow.respond(b,p,r.id,{version:1,action:'ACKNOWLEDGE',idempotencyKey:randomUUID()}),conflict);
    await assert.rejects(flow.resend(a,p,r.id,grant.id,{...revision,idempotencyKey:randomUUID()}),conflict);
    await assert.rejects(flow.resend(a,p,r.id,grant.id,{...revision,privateBody:'different'}),conflict);
    const ack={version:2,action:'ACKNOWLEDGE',idempotencyKey:randomUUID()};
    await flow.respond(b,p,r.id,ack);
    assert.equal((await requests.getPrivateRequest(b,r.id)).status,'ACKNOWLEDGED');
    assert.equal(await db.handoffResponse.count({where:{requestId:r.id}}),2);
    assert.equal((await flow.notifications(a,p)).filter(n=>n.kind==='ACKNOWLEDGED').length,1);
    const next=await flow.resend(a,p,r.id,grant.id,{expectedVersion:2,privateBody:'v3',idempotencyKey:randomUUID()});
    assert.equal(next.version,3);
    assert.equal((await requests.getPrivateRequest(b,r.id,2)).status,'ACKNOWLEDGED');
    const concurrent=await Promise.allSettled([flow.respond(b,p,r.id,{version:3,action:'ACKNOWLEDGE',idempotencyKey:randomUUID()}), flow.respond(b,p,r.id,{version:3,action:'REQUEST_CHANGES',comment:'private',idempotencyKey:randomUUID()})]);
    assert.equal(concurrent.filter(x=>x.status==='fulfilled').length,1);
    const raceRequest=await requests.createRequest(a,p,{recipientId:b,publicTitle:'race',privateBody:'v1',grantId:grant.id,idempotencyKey:randomUUID()});
    const competing=await Promise.allSettled([1,2].map(n=>flow.resend(a,p,raceRequest.id,grant.id,{expectedVersion:1,privateBody:'competing '+n,idempotencyKey:randomUUID()})));
    assert.equal(competing.filter(x=>x.status==='fulfilled').length,1);
    assert.equal(competing.filter(x=>x.status==='rejected'&&conflict(x.reason)).length,1);
    assert.equal(await db.handoffVersion.count({where:{requestId:raceRequest.id}}),2);
    assert.equal(await db.handoffNotification.count({where:{requestId:raceRequest.id,kind:'REVISION_RECEIVED'}}),1);
    const responseVsRevision=await Promise.allSettled([
      flow.respond(b,p,raceRequest.id,{version:2,action:'ACKNOWLEDGE',idempotencyKey:randomUUID()}),
      flow.resend(a,p,raceRequest.id,grant.id,{expectedVersion:2,privateBody:'v3',idempotencyKey:randomUUID()})
    ]);
    assert.equal(responseVsRevision[1].status,'fulfilled');
    const won=responseVsRevision[0].status==='fulfilled';
    if(!won)assert.ok(conflict(responseVsRevision[0].reason));
    assert.equal((await requests.getPrivateRequest(b,raceRequest.id)).status,'AWAITING_REVIEW');
    assert.equal((await requests.getPrivateRequest(b,raceRequest.id,2)).status,won?'ACKNOWLEDGED':'SUPERSEDED');
    assert.equal(await db.handoffResponse.count({where:{requestId:raceRequest.id}}),won?1:0);
    assert.equal(await db.handoffNotification.count({where:{requestId:raceRequest.id,kind:'ACKNOWLEDGED'}}),won?1:0);
    await db.projectMembership.delete({where:{projectId_userId:{projectId:p,userId:b}}});
    await assert.rejects(flow.resend(a,p,r.id,grant.id,{expectedVersion:3,privateBody:'v4',idempotencyKey:randomUUID()}));
    await assert.rejects(flow.notifications(b,p));
  } finally { await db.project.deleteMany({where:{id:p}}); await db.user.deleteMany({where:{id:{in:[a,b,c]}}}); await db.$disconnect(); }
});
